language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x

before_install:
  - go get -u github.com/haya14busa/goverage

script:
  - goverage -v -coverprofile=coverage.txt -covermode=count ./vm ./env . ./ast/astutil

after_success:
  - bash <(curl -s https://codecov.io/bash)
